-- 4
SELECT max(copii_totale) FROM (
  SELECT category, count(*) copii_totale
  FROM TITLE, TITLE_COPY, RENTAL
  WHERE TITLE.title_id = TITLE_COPY.title_id AND RENTAL.copy_id = TITLE_COPY.copy_id 
  GROUP BY category
);

-- 5
SELECT title, count(*)
FROM TITLE, TITLE_COPY
WHERE TITLE.title_id = TITLE_COPY.title_id
GROUP BY title;


-- 6
SELECT title, TITLE.TITLE_ID, TITLE_COPY.copy_id, status, 
  CASE WHEN status = 'RENTED' AND act_ret_date IS NULL THEN 'RENTED'
       ELSE 'AVAILABLE'
  END AS "CORRECT"
FROM TITLE, TITLE_COPY, RENTAL
WHERE TITLE.title_id = TITLE_COPY.title_id AND RENTAL.copy_id = TITLE_COPY.copy_id AND RENTAL.TITLE_ID = TITLE.TITLE_ID
ORDER BY TITLE_ID;

-- 7

SELECT COUNT(*)
FROM (
	SELECT title, TITLE.TITLE_ID, TITLE_COPY.copy_id, status, 
	  CASE WHEN status = 'RENTED' AND act_ret_date IS NULL THEN 'RENTED'
		   ELSE 'AVAILABLE'
	  END AS "CORRECT"
	FROM TITLE, TITLE_COPY, RENTAL
	WHERE TITLE.title_id = TITLE_COPY.title_id AND RENTAL.copy_id = TITLE_COPY.copy_id AND RENTAL.TITLE_ID = TITLE.TITLE_ID
	ORDER BY TITLE_ID
)
WHERE STATUS <> CORRECT;

-- 8
SELECT * FROM MEMBER
JOIN RESERVATION ON RESERVATION.MEMBER_ID = MEMBER.MEMBER_ID
JOIN RENTAL ON RENTAL.TITLE_ID = RESERVATION.TITLE_ID AND RENTAL.MEMBER_ID = RESERVATION.MEMBER_ID
JOIN TITLE_COPY ON RENTAL.COPY_ID = TITLE_COPY.COPY_ID AND TITLE_COPY.TITLE_ID = RENTAL.TITLE_ID;

SELECT FIRST_NAME, LAST_NAME, MEMBER_ID, RESERVATION.RES_DATE, TITLE.TITLE_ID, RENTAL.COPY_ID, BOOK_DATE,
  CASE WHEN RES_DATE = BOOK_DATE THEN 'DA'
    ELSE 'NU'
  END AS "WTF"
FROM (
  SELECT RENTAL.COPY_ID
  FROM MEMBER
  JOIN RESERVATION ON RESERVATION.MEMBER_ID = MEMBER.MEMBER_ID
  JOIN RENTAL ON RENTAL.TITLE_ID = RESERVATION.TITLE_ID AND RENTAL.MEMBER_ID = RESERVATION.MEMBER_ID
  JOIN TITLE_COPY ON RENTAL.COPY_ID = TITLE_COPY.COPY_ID AND TITLE_COPY.TITLE_ID = RENTAL.TITLE_ID
);
